from aiogram.types import ReplyKeyboardRemove

from .admin_keyboard import admin_keyboard
from .cancel import cancel_keyboard
from .change_default_questions_keyboard import change_default_questions_keyboard
from .FAQ_keyboard import faq_keyboard
from .answer_inline_keyboard import moderator_answer_keyboard
from .all_questions_keyboard import all_questions_keyboard
from .delete_moderator_keyboard import delete_moderator_keyboard
